// File generated by FlutterFire CLI — synced for app bootstrap.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import '../config/app_config.dart';

class DefaultFirebaseOptions {
  static bool get isConfigured => AppConfig.firebaseConfigured;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXzfYL-pyutRj28TJ2C-QE7jJaUfPGjmk',
    appId: '1:201364036111:web:c542a9825ca865f209a17a',
    messagingSenderId: '201364036111',
    projectId: 'emekachidimmawedding',
    authDomain: 'emekachidimmawedding.firebaseapp.com',
    storageBucket: 'emekachidimmawedding.firebasestorage.app',
    measurementId: 'G-PYGZBLP32R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCISZBO0v1wtJgTEfPgnXBD0RRFU2cIoYQ',
    appId: '1:201364036111:android:f1b2668c5e25f1d209a17a',
    messagingSenderId: '201364036111',
    projectId: 'emekachidimmawedding',
    storageBucket: 'emekachidimmawedding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbL26HQ06n3bs2fiQ2nVez7q-XZRnV_w0',
    appId: '1:201364036111:ios:1cbb28b9e2c2f96e09a17a',
    messagingSenderId: '201364036111',
    projectId: 'emekachidimmawedding',
    storageBucket: 'emekachidimmawedding.firebasestorage.app',
    iosBundleId: 'com.example.foreverMoments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbL26HQ06n3bs2fiQ2nVez7q-XZRnV_w0',
    appId: '1:201364036111:ios:1cbb28b9e2c2f96e09a17a',
    messagingSenderId: '201364036111',
    projectId: 'emekachidimmawedding',
    storageBucket: 'emekachidimmawedding.firebasestorage.app',
    iosBundleId: 'com.example.foreverMoments',
  );
}
